name: Publish

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          check-latest: true
          architecture: x64
          registry-url: 'https://registry.npmjs.org'
      - run: pnpm install --frozen-lockfile
      - run: pnpm -F "@nestjs-labs/nestjs-redis" run lint
      - run: pnpm -F "@nestjs-labs/nestjs-redis" run build
      - run: pnpm -r run publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
